import { readdirSync } from "fs";
import { join } from "path";
import type {
  AIProvider,
  EditImageInput,
  GenerateImageInput,
  GenerateMusicInput,
  ImageResult,
  MusicResult,
} from "./types";
import { uploadBytesToConvex } from "./convexUpload";

// Local-model provider (development only). Images run against an
// Automatic1111 / Forge-compatible Stable Diffusion HTTP API (the same
// txt2img/img2img endpoints Forge and A1111 expose). Generated bytes are
// pushed to Convex storage so they behave like any other card image.
//
// Music generation locally is the weak link, so we take the pragmatic route
// first: drop royalty-free tracks into /public/dev-tracks and this provider
// picks one deterministically per prompt. Wire a real MusicGen/ACE-Step
// backend later behind LOCAL_MUSIC_URL.

const NEGATIVE_PROMPT =
  "text, watermark, signature, blurry, low quality, deformed, extra limbs, ugly";

function imageBase() {
  const base = process.env.LOCAL_IMAGE_URL;
  if (!base) {
    throw new Error(
      "LOCAL_IMAGE_URL is not set. Point it at a running Stable Diffusion WebUI API (e.g. http://127.0.0.1:7860)."
    );
  }
  return base.replace(/\/$/, "");
}

async function fetchAsBase64(url: string): Promise<string> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch source image: ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  return buf.toString("base64");
}

// Deterministic small hash so the same prompt maps to the same dev track.
function hashString(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = (h * 31 + s.charCodeAt(i)) | 0;
  }
  return Math.abs(h);
}

export const localProvider: AIProvider = {
  name: "local",

  async generateImage({ prompt }: GenerateImageInput): Promise<ImageResult> {
    const res = await fetch(`${imageBase()}/sdapi/v1/txt2img`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        prompt: `high quality greeting card illustration: ${prompt}, professional card design, beautiful, detailed`,
        negative_prompt: NEGATIVE_PROMPT,
        width: 1024,
        height: 768,
        steps: 25,
        cfg_scale: 6,
        sampler_name: "DPM++ 2M Karras",
      }),
    });
    if (!res.ok) throw new Error(`Local image API error: ${res.status}`);

    const data = await res.json();
    const b64 = data?.images?.[0];
    if (!b64) throw new Error("Local image API returned no image");

    const url = await uploadBytesToConvex(
      new Uint8Array(Buffer.from(b64, "base64")),
      "image/png"
    );
    return { imageUrl: url, note: "Generated locally." };
  },

  async editImage({ prompt, imageUrl }: EditImageInput): Promise<ImageResult> {
    const initImage = await fetchAsBase64(imageUrl);
    const res = await fetch(`${imageBase()}/sdapi/v1/img2img`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        init_images: [initImage],
        prompt: `${prompt}, professional greeting card design, beautiful, high quality`,
        negative_prompt: NEGATIVE_PROMPT,
        denoising_strength: 0.6,
        width: 1024,
        height: 768,
        steps: 25,
        cfg_scale: 6,
        sampler_name: "DPM++ 2M Karras",
      }),
    });
    if (!res.ok) throw new Error(`Local img2img API error: ${res.status}`);

    const data = await res.json();
    const b64 = data?.images?.[0];
    if (!b64) throw new Error("Local img2img API returned no image");

    const url = await uploadBytesToConvex(
      new Uint8Array(Buffer.from(b64, "base64")),
      "image/png"
    );
    return { imageUrl: url, note: "Styled locally." };
  },

  async generateMusic({ prompt }: GenerateMusicInput): Promise<MusicResult> {
    // Deterministically pick a royalty-free track from /public/dev-tracks.
    try {
      const dir = join(process.cwd(), "public", "dev-tracks");
      const tracks = readdirSync(dir).filter((f) => /\.(mp3|ogg|wav|m4a)$/i.test(f));
      if (tracks.length === 0) {
        return {
          audioUrl: "",
          note: "No dev tracks found. Add audio files to /public/dev-tracks to use local music.",
        };
      }
      const pick = tracks[hashString(prompt) % tracks.length];
      return {
        audioUrl: `/dev-tracks/${pick}`,
        note: `Local dev track: ${pick}`,
      };
    } catch {
      return {
        audioUrl: "",
        note: "Local music unavailable. Create /public/dev-tracks with audio files.",
      };
    }
  },
};
